name: Deploy Manifests to EKS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Manifests
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 # Change to your region

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --name aifa --region ap-south-1

    - name: Deploy to Kubernetes
      run: |
        # Apply the namespace first if it doesn't exist
        kubectl create namespace game-2048 --dry-run=client -o yaml | kubectl apply -f -
        
        # Apply your deployment and service YAML
        kubectl apply -f manifest-file.yaml
        
        # Force a restart to ensure the latest version of the public image is pulled
        kubectl rollout restart deployment/deployment-2048 -n game-2048
